#!/bin/bash
clear

read parametry

 funkcja ()
 {

 echo "Melduje, że przyjąłem $# parametrów." 
 echo "Pierwszy: $1, trzeci: $3" 
 echo "Wszystkie: $@" 
 echo "To mówiłem ja: $0"
 echo "Znajduje się tutaj: $PWD"
}

funkcja $parametry