#!/bin/bash
clear

liczba0=0
liczba1=1
i=0
wynik1=$(($liczba0+$liczba1))

 echo $liczba0
 #sleep 2s 
 echo $liczba1

    while (( $liczba0+$liczba1 && $i<8 ))
    do
    liczba2=$(($liczba0+$liczba1))
    #sleep 2s
    echo $liczba2

    liczba0=$(($liczba1))
    liczba1=$(($liczba2))

    wynik2=$(($liczba1+$liczba2))
    
    ((i++))
    done

   wynik=$(($wynik1+$wynik2))
   echo "sdfdsf"
   echo $wynik
   echo "$@"
   echo "sdfdsf"
